name: Release
on: ["push"]
jobs:
  Release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Print GITHUB_WORKSPACE
        run: echo ${GITHUB_WORKSPACE}
